/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.northeastern.cs5610.recipe;

import static spark.Spark.*;


/**
 * The type App.
 */
public class App {

  /**
   * Gets assigned port.
   *
   * @return the assigned port
   */
  static int getAssignedPort() {
    ProcessBuilder processBuilder = new ProcessBuilder();
    if (processBuilder.environment().get("PORT") != null) {
      return Integer.parseInt(processBuilder.environment().get("PORT"));
    }
    return 5000; // run on port 5000 by default
  }

  /**
   * The entry point of application.
   *
   * @param arg the input arguments
   */
  public static void main(String[] arg) {
    // print all unhandled exceptions
    exception(Exception.class, (e, req, res) -> e.printStackTrace());

    // run on port 5000
    port(getAssignedPort());
    staticFiles.location("/public");

    // load and start the server
    DaggerServerComponent.create().server().start();
  }


}
